### ISSUE TITLE
Having troubles with installation

### ISSUE THREAD

**Issue by Nexonus** [Cartier1288/noise.aseprite-extension#1]
Hi there, I've been really excited about trying this plugin out but I stumble upon an issue with installation - At first I've tried to compile the project from the instructions, but I've kept getting stuck with CMakeList mismatching the one from source directory (I've selected src folder for that). I haven't used CMake before, so I'm pretty much trying my best to figure out how to follow up.

Then I've tried to install the already compiled version but it just gets stuck at the command prompt saying "Initializing Noise plugin" but nothing more happens afterwards. I don't have any option to generate it.

May I ask if I'm doing something wrong? I can't really figure out how exactly should I install this plugin. :) 
Thank you in advance!

**Comment by Nexonus** [comment]
Nevermind - This only happens for the latest version of Aseprite 1.40 or something like this it works fine for 1.3 Beta :)

**Comment by Cartier1288** [comment]
Hi, Nexonus.

Sorry for not getting back. I was away the week you posted the issue.

I am really glad to hear that it works fine for one of your installations of Aseprite. I am definitely concerned that it doesn't work for the latest though... Edit: I may have misunderstood, is the version that is working for you a newer version than the one that wasn't working, or did you have to downgrade?

May I ask which operating system you tried compiling the plugin on and also which C/C++ compiler it was using? Also just to confirm, did you follow the instructions for compiling in the README almost exactly? If you are still wanting to do your own compilation feel free to send any errors you are getting from CMake.

Right now I am working on a little extension to the plugin, so when I am done with that the first thing that I will do is address the issue with it not working in 1.40.

Thanks for letting me know about these issues btw.

**Comment by hedgewizards** [comment]
I just tried installing the latest win lua and dynamic releases and neither worked. 
the console pops up in a new tab with the text "initializing Noise plugin"
there's no error but the console stays open with only that one line, and I look under Edit-> and there's no "Generate" button

**Comment by Cartier1288** [comment]
Hey, @hedgewizards . Thanks for the feedback. 

What version of Windows and Aseprite are you using? I believe a lot of the Lua code used in the plugin requires very recent updates to Aseprites scripting functionality. I find that using unsupported functionality tends to fail quietly, so no error message isn't too surprising. You should also see a message saying "finished loading Noise plugin" in the console if everything loaded properly.

For reference, mine runs fine, and I am on Windows 10 and the Aseprite version I see when I click Help > About is: "Aseprite v1.3-rc6-x64"

**Comment by hedgewizards** [comment]
1.2.40-x64
That's the stable version on the steam release. For future readers:
Steam supports 1.3 via a beta branch. google how to switch to beta branch or:
- right click game in library
- properties
- Betas
- Beta Participation -> beta- v1.3 Beta Version
- Close & update app

working for me with the 1.3 beta

**Comment by Cartier1288** [comment]
@hedgewizards happy to hear you got it working! and thanks for the explanation for switching to beta. I never downloaded it from Steam, so I didn't know there was a difference. Cheers!
